/* Aplicação de filtro nas tabelas r_auto para retenção exclusiva de novas apólices */

\timing
\set xxx 16b

DROP TABLE IF EXISTS r_apolice_:xxx;

CREATE TABLE r_apolice_:xxx (
    cod_apo,
    endosso,
    cod_end,
    item,
    tipo_pes,
    modalidade,
    tipo_prod,
    cobertura,
    cod_modelo,
    ano_modelo,
    cod_tarif,
    regiao,
    cod_cont,
    tipo_franq,
    val_franq,
    perc_fator,
    tab_ref,
    is_casco,
    is_rcdmat,
    is_rcdc,
    is_rcdmor,
    is_app_ma,
    is_app_ipa,
    is_app_dmh,
    pre_casco,
    pre_casco_co,
    pre_rcdmat,
    pre_rcdc,
    pre_rcdmor,
    pre_app_ma,
    pre_app_ia,
    pre_app_dm,
    pre_outros,
    inicio_vig,
    fim_vig,
    perc_bonus,
    clas_bonus,
    perc_corr,
    sexo,
    data_nasc,
    tempo_hab,
    utilizacao,
    cep_util,
    cep_per
)
AS SELECT
    cod_apo,
    endosso,
    cod_end,
    item,
    tipo_pes,
    modalidade,
    tipo_prod,
    cobertura,
    cod_modelo,
    ano_modelo,
    cod_tarif,
    regiao,
    cod_cont,
    tipo_franq,
    val_franq,
    perc_fator,
    tab_ref,
    is_casco,
    is_rcdmat,
    is_rcdc,
    is_rcdmor,
    is_app_ma,
    is_app_ipa,
    is_app_dmh,
    pre_casco,
    pre_casco_co,
    pre_rcdmat,
    pre_rcdc,
    pre_rcdmor,
    pre_app_ma,
    pre_app_ia,
    pre_app_dm,
    pre_outros,
    inicio_vig,
    fim_vig,
    perc_bonus,
    clas_bonus,
    perc_corr,
    sexo,
    data_nasc,
    tempo_hab,
    utilizacao,
    cep_util,
    cep_per
FROM r_auto_:xxx
WHERE endosso = '0000000000';
